"""add performance indexes (motorbot, mbtrip, audit_events)

Revision ID: 586fe8452ca2
Revises: 70a550861017
Create Date: 2025-11-23 14:20:06.918230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586fe8452ca2'
down_revision: Union[str, Sequence[str], None] = '70a550861017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_MbTrip_Durum'), 'MbTrip', ['Durum'], unique=False)
    op.create_index(op.f('ix_MbTrip_MotorbotId'), 'MbTrip', ['MotorbotId'], unique=False)
    op.create_index(op.f('ix_MbTrip_SeferTarihi'), 'MbTrip', ['SeferTarihi'], unique=False)
    op.create_index(op.f('ix_Motorbot_Durum'), 'Motorbot', ['Durum'], unique=False)
    op.create_index(op.f('ix_Motorbot_Kod'), 'Motorbot', ['Kod'], unique=True)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_Motorbot_Kod'), table_name='Motorbot')
    op.drop_index(op.f('ix_Motorbot_Durum'), table_name='Motorbot')
    op.drop_index(op.f('ix_MbTrip_SeferTarihi'), table_name='MbTrip')
    op.drop_index(op.f('ix_MbTrip_MotorbotId'), table_name='MbTrip')
    op.drop_index(op.f('ix_MbTrip_Durum'), table_name='MbTrip')
    # ### end Alembic commands ###
